context('Basic Details page', () => {
  it('can see readonly fields', () => {
    cy.visit('/basic-details/37159b12-5c73-407a-94b6-43fc23938df6')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#name').should('contain.text', 'Mr Billy The Kid')
    cy.get('#date-of-birth').should('contain.text', '17/03/1980')
    cy.get('#address').should('contain.text', '281 Postal Default Street')
    cy.get('#address').should('contain.text', 'Postrict')
    cy.get('#address').should('contain.text', 'Postinton')
    cy.get('#address').should('contain.text', 'County Post')
    cy.get('#address').should('contain.text', 'NE30 3ZZ')
    cy.get('#date-of-home-visit').should('contain.text', '17/03/2025')
    cy.get('#other-address-1').should('contain.text', '2789 Main Street')
    cy.get('#other-address-1').should('contain.text', 'MainDistrict')
    cy.get('#other-address-1').should('contain.text', 'Maintown')
    cy.get('#other-address-1').should('contain.text', 'Maincounty')
    cy.get('#other-address-1').should('contain.text', 'MA30 3IN')
    cy.get('#phone-number').should('contain.text', '01912525252')
    cy.get('#mobile-number').should('contain.text', '07707123456')
    cy.get('#email-address').should('contain.text', 'test@test.com')
    cy.get('#employer-address').should('contain.text', 'Not Nice Officer')
    cy.get('#employer-address').should('contain.text', '19 Employer Street')
    cy.get('#employer-address').should('contain.text', 'Employer City')
    cy.get('#employer-address').should('contain.text', 'Emptrict')
    cy.get('#employer-address').should('contain.text', 'Emplounty')
    cy.get('#employer-address').should('contain.text', 'EM07 YER')
    cy.get('#employer-address').should('contain.text', '01332453294')
    cy.get('#ni-number').should('contain.text', 'XX000000X')
  })

  it('can see buttons', () => {
    cy.visit('/basic-details/37159b12-5c73-407a-94b6-43fc23938df6')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#continue-button').should('contain.text', 'Continue')
    cy.get('#close-button').should('contain.text', 'Save Progress and Close')
    cy.get('#refresh-from-ndelius--button').should('contain.text', 'Refresh from Delius')
  })

  it('When no DWP address present, add address button should display with correct navigation', () => {
    cy.visit('/basic-details/37159b12-5c73-407a-94b6-43fc23938df6')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#dwp-address').should('not.exist')
    cy.get('#add-address-button').should('exist').should('be.visible')
    cy.get('#update-address-button').should('not.exist')
    cy.get('#add-address-button').should('contain.text', 'Add Address')
    cy.get('#add-address-button').click()
    cy.url().should('include', '/add-dwp-address/37159b12-5c73-407a-94b6-43fc23938df6')
  })

  it('should display DWP address and update address button if present with navigation', () => {
    cy.visit('/basic-details/f42ca70c-8c2e-4def-be06-a455d1034467')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#dwp-address').should('exist').should('be.visible')
    cy.get('#dwp-address').should('contain.text', 'A Fun DWP Location')
    cy.get('#dwp-address').should('contain.text', '67 DWPStreet')
    cy.get('#dwp-address').should('contain.text', 'Ment District')
    cy.get('#dwp-address').should('contain.text', 'Depart Town')
    cy.get('#dwp-address').should('contain.text', 'Work County')
    cy.get('#dwp-address').should('contain.text', 'PE45 5NS')
    cy.get('#add-address-button').should('not.exist')
    cy.get('#update-address-button').should('exist').should('be.visible')
    cy.get('#update-address-button').should('contain.text', 'Update Address')
    cy.get('#update-address-button').click()
    cy.url().should('include', '/add-dwp-address/f42ca70c-8c2e-4def-be06-a455d1034467')
  })

  it('refresh button performs a post request then reloads the screen', () => {
    cy.intercept('POST', '/basic-details/**').as('refreshRequest')
    cy.visit('/basic-details/ffa7f42c-b355-4a6c-8668-4e4fe6d77b06')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#name').should('contain.text', 'Mr Billy The Kid')
    cy.get('#refresh-from-ndelius--button').click()
    cy.wait('@refreshRequest')
    cy.url().should('include', '/basic-details/ffa7f42c-b355-4a6c-8668-4e4fe6d77b06')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#name').should('contain.text', 'Mr Billy The Kid')
  })

  it('close button performs a post request and displays message', () => {
    cy.intercept('POST', '/basic-details/**').as('saveAndCloseRequest')
    cy.visit('/basic-details/4146ad41-8a05-45c1-b593-d5c7e22c9625')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#name').should('contain.text', 'Mr Billy The Kid')
    cy.get('#close-button').click()
    cy.wait('@saveAndCloseRequest').then(({ request }) => {
      const body = new URLSearchParams(request.body)
      expect(body.get('action')).to.equal('saveProgressAndClose')
    })
    cy.contains('You can now safely close this window').should('be.visible')
    cy.get('#page-title').should('not.exist')
  })

  it('continue button performs a post and redirects to risk assessment page', () => {
    cy.intercept('POST', '/basic-details/**').as('formSubmit')
    cy.visit('/basic-details/bf77620c-d913-4e62-9150-0c54486d78cc')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#continue-button').click()
    cy.wait('@formSubmit')
    cy.url().should('include', '/risk-assessment/bf77620c-d913-4e62-9150-0c54486d78cc')
  })

  it('should return to check your report if came from check your report', () => {
    cy.intercept('POST', '/basic-details/**').as('formSubmit')
    cy.visit('/basic-details/96bcb64c-df61-4887-a2f5-76ca61ec8b3d?returnTo=check-your-report')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#continue-button').click()
    cy.wait('@formSubmit')
    cy.url().should('include', '/check-your-report/96bcb64c-df61-4887-a2f5-76ca61ec8b3d')
  })

  it('should display deeplink when no valid addresses present', () => {
    cy.visit('/basic-details/5c17706e-a8ec-4276-8755-9b866f751e04')
    cy.url().should('include', '/basic-details')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Basic Details')
    cy.get('#address').should('not.exist')
    cy.get('#no-address-found').should('exist').should('contain.text', 'No Postal Address found in National Delius')
    cy.get('#add-address--deeplink')
      .should('exist')
      .should('contain.text', 'Click this hyperlink to open a new tab to add an address to Delius')
    cy.get('#add-address--deeplink').should('have.attr', 'href').and('include', 'component=AddressandAccommodation')
  })

  it('should stay on page and show NDelius error message if 500 thrown from NDelius integration service', () => {
    cy.visit('/basic-details/67006838-34e7-41b8-8ea9-5bec66106041')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains('There has been a problem fetching information from NDelius. Please try again later.').should('exist')
  })

  it('should stay on page and show Service error message if 500 thrown from Service', () => {
    cy.visit('/basic-details/d6cbd844-28e9-4fcb-82db-f50bd335b7f9')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains(
      'There has been a problem fetching information from the Warrant Risk Assessment Service. Please try again later.',
    ).should('exist')
  })

  it('should show error page with message if 400 error returned from integrations crn not existing', () => {
    cy.visit('/basic-details/d378bbc3-7032-4a4d-9cba-94eb49fef1bc')
    cy.url().should('include', '/basic-details')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains(
      'An unexpected 400 type error has occurred. Please contact the service desk and report this error.',
    ).should('exist')
  })
})
