context('Check your answers data checks', () => {
  it('Basic Details not saved', () => {
    cy.visit(`/check-your-answers/9f3e2c7a-6c1d-4f58-9a12-5e7b3d2c8f41`)
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-basic-details').should('not.exist')
    cy.get('#cya-link-title-and-name').should('not.exist')
    cy.get('#cya-link-postal-address').should('not.exist')
    cy.get('#cya-link-date-of-birth').should('not.exist')
    cy.get('#cya-link-employer-address').should('not.exist')
    cy.get('#cya-link-national-insurance-number').should('not.exist')
  })

  it('Basic Details not populated', () => {
    cy.visit(`/check-your-answers/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-basic-details').should('exist')
    cy.get('#change-risk-summary').should('not.exist')
    cy.get('#change-risk-assessment').should('not.exist')
    cy.get('#change-warrant-execution').should('not.exist')
    cy.get('#cya-link-title-and-name').should('exist')
    cy.get('#cya-link-postal-address').should('exist')
    cy.get('#cya-link-dwp-address').should('exist')
    cy.get('#cya-link-date-of-birth').should('exist')
    cy.get('#cya-link-employer-address').should('exist')
    cy.get('#cya-link-national-insurance-number').should('exist')
    cy.get('#cya-link-title-and-name').click()
    cy.url().should('include', `/basic-details/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.visit(`/check-your-answers/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.get('#cya-link-postal-address').click()
    cy.url().should('include', `/basic-details/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.visit(`/check-your-answers/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.get('#cya-link-date-of-birth').click()
    cy.url().should('include', `/basic-details/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.visit(`/check-your-answers/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.get('#cya-link-employer-address').click()
    cy.url().should('include', `/basic-details/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.visit(`/check-your-answers/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.get('#cya-link-dwp-address').click()
    cy.url().should('include', `/basic-details/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.visit(`/check-your-answers/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.get('#cya-link-national-insurance-number').click()
    cy.url().should('include', `/basic-details/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
    cy.visit(`/check-your-answers/1a7c5e92-3d44-4b61-8fe0-2c9d7a5b6e13`)
  })

  it('Basic Details is populated', () => {
    cy.visit(`/check-your-answers/d3b8f1a4-7e22-4c9b-9351-6f0a2d8e4b77`)
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-basic-details').should('exist')
    cy.get('#change-risk-summary').should('not.exist')
    cy.get('#change-risk-assessment').should('not.exist')
    cy.get('#change-warrant-execution').should('not.exist')
    cy.get('#cya-link-title-and-name').should('not.exist')
    cy.get('#cya-link-postal-address').should('not.exist')
    cy.get('#cya-link-dwp-address').should('not.exist')
    cy.get('#cya-link-date-of-birth').should('not.exist')
    cy.get('#cya-link-employer-address').should('not.exist')
    cy.get('#cya-link-national-insurance-number').should('not.exist')
    cy.get('#change-basic-details').click()
    cy.url().should('include', `/basic-details/d3b8f1a4-7e22-4c9b-9351-6f0a2d8e4b77`)
    cy.visit(`/check-your-answers/d3b8f1a4-7e22-4c9b-9351-6f0a2d8e4b77`)
  })

  it('Risk Assessment not saved', () => {
    cy.visit('/check-your-answers/6c2f4e9a-1b73-4d88-9f20-3a5c7e1d4b6f')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-risk-assessment').should('not.exist')
    cy.get('#cya-link-mappa-procedures').should('not.exist')
    cy.get('#cya-link-high-risk-of-self-harm').should('not.exist')
    cy.get('#cya-link-high-risk-of-absconding').should('not.exist')
    cy.get('#cya-link-vulnerable').should('not.exist')
    cy.get('#cya-link-carry-or-use-weapons').should('not.exist')
    cy.get('#cya-link-assaulting-police').should('not.exist')
    cy.get('#cya-link-misuse-drugs-or-alcohol').should('not.exist')
  })

  it('Risk Assessment not populated', () => {
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-risk-assessment').should('exist')
    cy.get('#change-risk-summary').should('not.exist')
    cy.get('#change-warrant-execution').should('not.exist')
    cy.get('#cya-link-mappa-procedures').should('exist')
    cy.get('#cya-link-high-risk-of-self-harm').should('exist')
    cy.get('#cya-link-high-risk-of-absconding').should('exist')
    cy.get('#cya-link-vulnerable').should('exist')
    cy.get('#cya-link-carry-or-use-weapons').should('exist')
    cy.get('#cya-link-assaulting-police').should('exist')
    cy.get('#cya-link-misuse-drugs-or-alcohol').should('exist')
    cy.get('#cya-link-mappa-procedures').click()
    cy.url().should('include', '/risk-assessment/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.get('#cya-link-high-risk-of-self-harm').click()
    cy.url().should('include', '/risk-assessment/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.get('#cya-link-high-risk-of-absconding').click()
    cy.url().should('include', '/risk-assessment/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.get('#cya-link-vulnerable').click()
    cy.url().should('include', '/risk-assessment/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.get('#cya-link-carry-or-use-weapons').click()
    cy.url().should('include', '/risk-assessment/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.get('#cya-link-assaulting-police').click()
    cy.url().should('include', '/risk-assessment/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.get('#cya-link-misuse-drugs-or-alcohol').click()
    cy.url().should('include', '/risk-assessment/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
  })

  it('Risk Assessment populated', () => {
    cy.visit('/check-your-answers/f4b8a2d6-9c31-4e75-b0a4-1d7f3c5e8a92')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-risk-assessment').should('exist')
    cy.get('#change-risk-summary').should('not.exist')
    cy.get('#change-warrant-execution').should('not.exist')
    cy.get('#cya-link-mappa-procedures').should('not.exist')
    cy.get('#cya-link-high-risk-of-self-harm').should('not.exist')
    cy.get('#cya-link-high-risk-of-absconding').should('not.exist')
    cy.get('#cya-link-vulnerable').should('not.exist')
    cy.get('#cya-link-carry-or-use-weapons').should('not.exist')
    cy.get('#cya-link-assaulting-police').should('not.exist')
    cy.get('#cya-link-misuse-drugs-or-alcohol').should('not.exist')
    cy.get('#change-risk-assessment').click()
    cy.url().should('include', '/risk-assessment/f4b8a2d6-9c31-4e75-b0a4-1d7f3c5e8a92')
    cy.visit('/check-your-answers/f4b8a2d6-9c31-4e75-b0a4-1d7f3c5e8a92')
  })

  it('Risk Summary not saved', () => {
    cy.visit('/check-your-answers/7e1a4c9d-2b63-4f58-9a70-3d5c8e1b6f24')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-risk-summary').should('not.exist')
    cy.get('#cya-link-risk-to-public').should('not.exist')
    cy.get('#cya-link-risk-to-enforcement-officers').should('not.exist')
    cy.get('#cya-link-risk-to-police').should('not.exist')
  })

  it('Risk Summary not populated', () => {
    cy.visit('/check-your-answers/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-risk-summary').should('exist')
    cy.get('#change-warrant-execution').should('not.exist')
    cy.get('#cya-link-risk-to-public').should('exist')
    cy.get('#cya-link-risk-to-enforcement-officers').should('exist')
    cy.get('#cya-link-risk-to-police').should('exist')
    cy.get('#cya-link-risk-to-public').click()
    cy.url().should('include', '/risk-summary/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
    cy.visit('/check-your-answers/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
    cy.get('#cya-link-risk-to-enforcement-officers').click()
    cy.url().should('include', '/risk-summary/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
    cy.visit('/check-your-answers/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
    cy.get('#cya-link-risk-to-police').click()
    cy.url().should('include', '/risk-summary/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
    cy.visit('/check-your-answers/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
  })

  it('Risk Summary populated', () => {
    cy.visit('/check-your-answers/2d6f9a3b-1c84-4e57-b290-5a7e3c1d8f46')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-risk-summary').should('exist')
    cy.get('#change-warrant-execution').should('not.exist')
    cy.get('#cya-link-risk-to-public').should('not.exist')
    cy.get('#cya-link-risk-to-enforcement-officers').should('not.exist')
    cy.get('#cya-link-risk-to-police').should('not.exist')
    cy.get('#change-risk-summary').click()
    cy.url().should('include', '/risk-summary/2d6f9a3b-1c84-4e57-b290-5a7e3c1d8f46')
    cy.visit('/check-your-answers/2d6f9a3b-1c84-4e57-b290-5a7e3c1d8f46')
  })

  it('Warrant Execution not saved', () => {
    cy.visit('/check-your-answers/3b7d1e9a-6c24-4f58-8a10-2d5e7c9b4a31')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-warrant-execution').should('not.exist')
    cy.get('#cya-link-responsible-officer').should('not.exist')
    cy.get('#cya-link-probation-area').should('not.exist')
    cy.get('#cya-link-signature-and-date').should('not.exist')
  })

  it('Warrant Execution not populated', () => {
    cy.visit('/check-your-answers/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-warrant-execution').should('exist')
    cy.get('#cya-link-responsible-officer').should('exist')
    cy.get('#cya-link-probation-area').should('exist')
    cy.get('#cya-link-signature-and-date').should('exist')
    cy.get('#cya-link-responsible-officer').click()
    cy.url().should('include', '/warrant-execution/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.visit('/check-your-answers/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.get('#cya-link-probation-area').click()
    cy.url().should('include', '/warrant-execution/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.visit('/check-your-answers/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.get('#cya-link-signature-and-date').click()
    cy.url().should('include', '/warrant-execution/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.visit('/check-your-answers/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
  })

  it('Warrant Execution populated', () => {
    cy.visit('/check-your-answers/5d9c2a7e-1f34-4b68-8e90-3a6d1c7f4b25')
    cy.url().should('include', '/check-your-answers')
    cy.get('#page-title').should('contain.text', 'Check Your Answers')
    cy.get('#change-warrant-execution').should('exist')
    cy.get('#cya-link-responsible-officer').should('not.exist')
    cy.get('#cya-link-probation-area').should('not.exist')
    cy.get('#cya-link-signature-and-date').should('not.exist')
    cy.get('#change-warrant-execution').click()
    cy.url().should('include', '/warrant-execution/5d9c2a7e-1f34-4b68-8e90-3a6d1c7f4b25')
    cy.visit('/check-your-answers/5d9c2a7e-1f34-4b68-8e90-3a6d1c7f4b25')
  })

  it('Publish only available when completed', () => {
    cy.visit('/check-your-answers/9f3e2c7a-6c1d-4f58-9a12-5e7b3d2c8f41')
    cy.get('#publish').should('not.exist')
    cy.visit('/check-your-answers/a1d9c3f7-5e24-4b68-8a91-2f6e3c7b4d10')
    cy.get('#publish').should('not.exist')
    cy.visit('/check-your-answers/c8f3d2a1-5e47-4b69-8c10-2a7d6e4f9b35')
    cy.get('#publish').should('not.exist')
    cy.visit('/check-your-answers/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.get('#publish').should('not.exist')
    cy.visit('/check-your-answers/4a1e9d3c-7b25-4f68-9c10-2d6e8a5b3f41')
    cy.get('#publish').should('exist')
  })

  it('should show relevant buttons when report is Validated and publish button should redirect correctly', () => {
    cy.visit('/check-your-answers/7c5a2d91-4e3f-48b6-9a20-1d6e8b4f3c72')
    cy.get('#publish').should('exist')
    cy.get('#deleteDraft')
      .should('exist')
      .should('have.attr', 'href', '/confirm-delete/7c5a2d91-4e3f-48b6-9a20-1d6e8b4f3c72')
    cy.get('#viewDraft').should('exist').should('have.attr', 'href', '/pdf/7c5a2d91-4e3f-48b6-9a20-1d6e8b4f3c72')
    cy.get('#publish').click()
    cy.url().should('include', '/report-completed/7c5a2d91-4e3f-48b6-9a20-1d6e8b4f3c72')
  })

  it('should show relevant buttons when report is not Validated', () => {
    cy.visit('/check-your-answers/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.get('#publish').should('not.exist')
    cy.get('#deleteDraft')
      .should('exist')
      .should('have.attr', 'href', '/confirm-delete/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
    cy.get('#viewDraft').should('exist').should('have.attr', 'href', '/pdf/8a2f6c1d-4b73-49e5-9c20-1d7e3a5b6f42')
  })

  it('navigates to report completed page if completed date set', () => {
    cy.visit('/check-your-answers/72d2199f-4b5f-4a1d-a1ca-44ede214c729')
    cy.url().should('include', '/report-completed/72d2199f-4b5f-4a1d-a1ca-44ede214c729')
  })
})
