context('Risk Assessment page', () => {
  it('can see fields and radio buttons with yes defaulting', () => {
    cy.visit('/risk-assessment/bbb48e8d-bd0d-4750-ad0c-2abbef3d2318')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#mappaDetails .govuk-details__summary-text')
      .should('be.visible')
      .should('contain.text', 'Click here to view MAPPA information')
    cy.get('#mappaDetails .govuk-details__summary-text').click()
    cy.get('#mappaDetails .govuk-details__text')
      .cleanText()
      .should('include', 'MAPPA Category: MAPPA Level 1')
      .and('include', 'Date: 01/01/2025')
    cy.get('input[name="mappaRadio"][value="Yes"]').should('be.checked')
    cy.get('input[name="mappaRadio"][value="No"]').should('not.be.checked')
    cy.get('#selfHarmDetails .govuk-details__summary-text')
      .should('be.visible')
      .should('contain.text', 'Click here to view Self Harm information')
    cy.get('#selfHarmDetails .govuk-details__summary-text').click()
    cy.get('#selfHarmDetails .govuk-details__text')
      .cleanText()
      .should('include', 'Risk: No')
      .and('include', "Previous: Don't know")
      .and('include', 'Previous Concerns Notes: Risk of self harms concerns due to harm')
      .and('include', 'Current: Yes')
      .and('include', 'Current Concerns Notes: Risk of self harms concerns due to self')
    cy.get('input[name="selfHarmRadio"][value="Yes"]').should('be.checked')
    cy.get('input[name="selfHarmRadio"][value="No"]').should('not.be.checked')
    cy.get('#abscondingDetails .govuk-details__summary-text')
      .should('be.visible')
      .should('contain.text', 'Click here to view absconding information')
    cy.get('#abscondingDetails .govuk-details__summary-text').click()
    cy.get('#abscondingDetails .govuk-details__text').cleanText().should('include', 'Escape or Abscond risk: YES')
    cy.get('input[name="abscondRadio"][value="Yes"]').should('be.checked')
    cy.get('input[name="abscondRadio"][value="No"]').should('not.be.checked')
    cy.get('#vulnerabilityDetails .govuk-details__summary-text')
      .should('be.visible')
      .should('contain.text', 'Click here to view Vulnerability information')
    cy.get('#vulnerabilityDetails .govuk-details__summary-text').click()
    cy.get('#vulnerabilityDetails .govuk-details__text')
      .cleanText()
      .should('include', "Risk: Don't know")
      .and('include', 'Previous: No')
      .and('include', 'Previous Concerns Notes: Risk of self harms concerns due to vulner')
      .and('include', 'Current: Yes')
      .and('include', 'Current Concerns Notes: Risk of self harms concerns due to ability')
    cy.get('input[name="vulnerableRadio"][value="Yes"]').should('be.checked')
    cy.get('input[name="vulnerableRadio"][value="No"]').should('not.be.checked')
    cy.get('#weaponDetails .govuk-details__summary-text')
      .should('be.visible')
      .should('contain.text', 'Click here to view relevant information')
    cy.get('#weaponDetails .govuk-details__summary-text').click()
    cy.get('#weaponDetails .govuk-details__text')
      .cleanText()
      .should('include', 'Pattern of offending: Pattern')
      .and('include', 'Offence involved: WOUNDING')
      .and('include', 'Specific weapon: BIG KNIVES')
    cy.get('input[name="weaponRadio"][value="Yes"]').should('be.checked')
    cy.get('input[name="weaponRadio"][value="No"]').should('not.be.checked')
    cy.get('#policeDetails .govuk-details__summary-text')
      .should('be.visible')
      .should('contain.text', 'Click here to view information')
    cy.get('#policeDetails .govuk-details__summary-text').click()
    cy.get('#policeDetails .govuk-details__text')
      .cleanText()
      .should('include', 'Risk to Children: HIGH')
      .and('include', 'Risk to Known Adult: HIGH')
      .and('include', 'Risk to Prisoners: LOW')
      .and('include', 'Risk to Staff: MEDIUM')
      .and('include', 'Risk to Public: HIGH')
    cy.get('input[name="policeRadio"][value="Yes"]').should('be.checked')
    cy.get('input[name="policeRadio"][value="No"]').should('not.be.checked')
    cy.get('#drugDetails .govuk-details__summary-text')
      .should('be.visible')
      .should('contain.text', 'Click here to view drug misuse information')
    cy.get('#drugDetails .govuk-details__summary-text').click()
    cy.get('#drugDetails .govuk-details__text')
      .cleanText()
      .should('include', 'Name: Drug misuse')
      .and('include', 'Risk of Harm: No')
      .and('include', 'Risk of Reoffending: No')
      .and('include', 'Severity: SEVERE')
    cy.get('input[name="drugMisuseRadio"][value="Yes"]').should('be.checked')
    cy.get('input[name="drugMisuseRadio"][value="No"]').should('not.be.checked')
  })

  it('can see buttons', () => {
    cy.visit('/risk-assessment/bbb48e8d-bd0d-4750-ad0c-2abbef3d2318')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#continue-button').should('contain.text', 'Continue')
    cy.get('#close-button').should('contain.text', 'Save Progress and Close')
    cy.get('#refresh-from-ndelius--button').should('contain.text', 'Refresh from Delius and OASys')
  })

  it('Detail Dropdowns should display None found when no information returned and radio buttons to no', () => {
    cy.visit('/risk-assessment/fe1580f4-e231-4caa-9afc-3f1bf07b7313')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#mappaDetails .govuk-details__summary-text').click()
    cy.get('#mappaDetails .govuk-details__text').should('contain.text', 'None Found')
    cy.get('input[name="mappaRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="mappaRadio"][value="No"]').should('be.checked')
    cy.get('#selfHarmDetails .govuk-details__summary-text').click()
    cy.get('#selfHarmDetails .govuk-details__text').should('contain.text', 'None Found')
    cy.get('input[name="selfHarmRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="selfHarmRadio"][value="No"]').should('be.checked')
    cy.get('#abscondingDetails .govuk-details__summary-text').click()
    cy.get('#abscondingDetails .govuk-details__text').should('contain.text', 'None Found')
    cy.get('input[name="abscondRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="abscondRadio"][value="No"]').should('be.checked')
    cy.get('#vulnerabilityDetails .govuk-details__summary-text').click()
    cy.get('#vulnerabilityDetails .govuk-details__text').should('contain.text', 'None Found')
    cy.get('input[name="vulnerableRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="vulnerableRadio"][value="No"]').should('be.checked')
    cy.get('#weaponDetails .govuk-details__summary-text').click()
    cy.get('#weaponDetails .govuk-details__text').should('contain.text', 'None Found')
    cy.get('input[name="weaponRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="weaponRadio"][value="No"]').should('be.checked')
    cy.get('#policeDetails .govuk-details__summary-text').click()
    cy.get('#policeDetails .govuk-details__text').should('contain.text', 'None Found')
    cy.get('input[name="policeRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="policeRadio"][value="No"]').should('be.checked')
    cy.get('#drugDetails .govuk-details__summary-text').click()
    cy.get('#drugDetails .govuk-details__text').should('contain.text', 'None Found')
    cy.get('input[name="drugMisuseRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="drugMisuseRadio"][value="No"]').should('be.checked')
  })

  it('Radio buttons should always default to selection stored in DB', () => {
    cy.visit('/risk-assessment/29ad8c34-0aef-440e-9104-64c6967c2c47')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#mappaDetails .govuk-details__summary-text').click()
    cy.get('#mappaDetails .govuk-details__text').should('not.contain.text', 'None Found')
    cy.get('input[name="mappaRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="mappaRadio"][value="No"]').should('be.checked')
    cy.get('#selfHarmDetails .govuk-details__summary-text').click()
    cy.get('#selfHarmDetails .govuk-details__text').should('not.contain.text', 'None Found')
    cy.get('input[name="selfHarmRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="selfHarmRadio"][value="No"]').should('be.checked')
    cy.get('#abscondingDetails .govuk-details__summary-text').click()
    cy.get('#abscondingDetails .govuk-details__text').should('not.contain.text', 'None Found')
    cy.get('input[name="abscondRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="abscondRadio"][value="No"]').should('be.checked')
    cy.get('#vulnerabilityDetails .govuk-details__summary-text').click()
    cy.get('#vulnerabilityDetails .govuk-details__text').should('not.contain.text', 'None Found')
    cy.get('input[name="vulnerableRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="vulnerableRadio"][value="No"]').should('be.checked')
    cy.get('#weaponDetails .govuk-details__summary-text').click()
    cy.get('#weaponDetails .govuk-details__text').should('not.contain.text', 'None Found')
    cy.get('input[name="weaponRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="weaponRadio"][value="No"]').should('be.checked')
    cy.get('#policeDetails .govuk-details__summary-text').click()
    cy.get('#policeDetails .govuk-details__text').should('not.contain.text', 'None Found')
    cy.get('input[name="policeRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="policeRadio"][value="No"]').should('be.checked')
    cy.get('#drugDetails .govuk-details__summary-text').click()
    cy.get('#drugDetails .govuk-details__text').should('not.contain.text', 'None Found')
    cy.get('input[name="drugMisuseRadio"][value="Yes"]').should('not.be.checked')
    cy.get('input[name="drugMisuseRadio"][value="No"]').should('be.checked')
  })

  it('refresh button performs a post request then reloads the screen', () => {
    cy.intercept('POST', '/risk-assessment/**').as('refreshRequest')
    cy.visit('/risk-assessment/ed6466c1-b6de-4401-abd8-8fbd35a71662')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#refresh-from-ndelius--button').click()
    cy.wait('@refreshRequest')
    cy.url().should('include', '/risk-assessment/ed6466c1-b6de-4401-abd8-8fbd35a71662')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
  })

  it('close button performs a post request and displays message', () => {
    cy.intercept('POST', '/risk-assessment/**').as('saveAndCloseRequest')
    cy.visit('/risk-assessment/bde9b9c5-bf47-4337-aff3-c4f0ca7c6642')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#close-button').click()
    cy.wait('@saveAndCloseRequest').then(({ request }) => {
      const body = new URLSearchParams(request.body)
      expect(body.get('action')).to.equal('saveProgressAndClose')
    })
    cy.contains('You can now safely close this window').should('be.visible')
    cy.get('#page-title').should('not.exist')
  })

  it('continue button performs a post and redirects to risk summary page', () => {
    cy.intercept('POST', '/risk-assessment/**').as('formSubmit')
    cy.visit('/risk-assessment/bb9d0aff-7b6c-4239-99cb-32672e47b4f5')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#continue-button').click()
    cy.wait('@formSubmit')
    cy.url().should('include', '/risk-summary/bb9d0aff-7b6c-4239-99cb-32672e47b4f5')
  })

  it('should return to check your report if came from check your report', () => {
    cy.intercept('POST', '/risk-assessment/**').as('formSubmit')
    cy.visit('/risk-assessment/b5cebf44-b000-46a6-921a-6f8cfc45e0d5?returnTo=check-your-report')
    cy.url().should('include', '/risk-assessment')
    cy.get('#page-title').should('contain.text', 'Warrant Risk Assessment - Risk Assessment')
    cy.get('#continue-button').click()
    cy.wait('@formSubmit')
    cy.url().should('include', '/check-your-report/b5cebf44-b000-46a6-921a-6f8cfc45e0d5')
  })

  it('should stay on page and show NDelius error message if 500 thrown from NDelius integration service', () => {
    cy.visit('/risk-assessment/67006838-34e7-41b8-8ea9-5bec66106041')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains('There has been a problem fetching information from NDelius. Please try again later.').should('exist')
  })

  it('should stay on page and show ARNS error message if 500 thrown from ARNS service', () => {
    cy.visit('/risk-assessment/047bf972-a6c3-4253-ac16-2ea344d8da51')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains(
      'There has been a problem fetching information from Assess Risk and Needs Service. Please try again later.',
    ).should('exist')
  })

  it('should stay on page and show Service error message if 500 thrown from WRA Service', () => {
    cy.visit('/risk-assessment/d6cbd844-28e9-4fcb-82db-f50bd335b7f9')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains(
      'There has been a problem fetching information from the Warrant Risk Assessment Service. Please try again later.',
    ).should('exist')
  })

  it('should show error page with message if 400 error returned from integrations crn not existing', () => {
    cy.visit('/risk-assessment/d378bbc3-7032-4a4d-9cba-94eb49fef1bc')
    cy.url().should('include', '/risk-assessment')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains(
      'An unexpected 400 type error has occurred. Please contact the service desk and report this error.',
    ).should('exist')
  })

  it('should show error page with message if 400 error returned from ARNS service from crn not existing', () => {
    cy.visit('/risk-assessment/d378bbc3-7032-4a4d-9cba-94eb49fef1bc')
    cy.url().should('include', '/risk-assessment')
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.contains(
      'An unexpected 400 type error has occurred. Please contact the service desk and report this error.',
    ).should('exist')
  })
})
